# Use root/example as user/password credentials
version: '3.1'

services:
  rabbitmq:
      image: rabbitmq:management
      hostname: rabbitmq
      ports:
          - 5672:5672
          - 15672:15672
      volumes:
          - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
      environment:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
  ibmmq:
    image: ibmcom/mq:latest
    ports:
      - 1414:1414
      - 9443:9443
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: "DevManager"
      MQ_APP_PASSWORD: "app"
      MQ_ADMIN_PASSWORD: "password"
