inboundRabbitMQConfigurations: 
  url: "amqp://guest:guest@localhost:5672/"
  exchangeName: "inbound"
  queueName: "inboundQueue"
outboundRabbitMQConfigurations: 
  url: "amqp://guest:guest@localhost:5672/"
  exchangeName: "outbound"
  queueName: "outboundQueue"